<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Project 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Project 2_Final_files/libs/clipboard/clipboard.min.js"></script>
<script src="Project 2_Final_files/libs/quarto-html/quarto.js"></script>
<script src="Project 2_Final_files/libs/quarto-html/popper.min.js"></script>
<script src="Project 2_Final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Project 2_Final_files/libs/quarto-html/anchor.min.js"></script>
<link href="Project 2_Final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Project 2_Final_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Project 2_Final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Project 2_Final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Project 2_Final_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project 2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="brief-project-description" class="level3">
<h3 class="anchored" data-anchor-id="brief-project-description">Brief Project Description</h3>
<p>Hi, my name is Jacob Kawalski and I have just started a real estate business. But I am new to this area of work, and I need to understand the real estate market. Luckily, I have been blessed with a data set of different variables of houses in king county. But I need help of some business analyst to understand and explore this data set. Plus find the prices of these new houses!</p>
<p>I called my friend Master Yeoda and asked if he could help. Unfortunate Master Yeoda could not help because he got too full of eating shrimp pasta. But he recommended three students Tai, Simon, and Marcus and said, “they are some of the funniest students in my class, I am sure they will help”.</p>
<p>After reaching out to Tai, Simon and Marcus, they gave me an appropriate model to understand the data set. They also helped me predict the price of the new houses in the data set. These 3 are the best and I am so thankful for this recommendation.</p>
</section>
<section id="objective" class="level3">
<h3 class="anchored" data-anchor-id="objective">Objective</h3>
<p>From Tai, Simon, and Marcus</p>
<p>Hi Jacob, we will love to help! Thanks for reaching out.</p>
<p>Below we have attached the analytical thinking we did to this data set. We included 3 different models to help us predict the target variable. And we included the reason why we picked these models because we wanted to help you understand our thinking. We validated and evaluated the models as well to understand which one is the best. Then, we used the best model to predict the price of the new houses. We hope this helps and good luck with the real estate business!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ lubridate 1.9.2     ✔ tibble    3.2.1
✔ purrr     1.0.1     ✔ tidyr     1.3.0
✔ readr     2.1.4     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ purrr::lift()   masks caret::lift()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:purrr':

    some

The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(carData)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loaded ROSE 0.0-4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrgram)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'corrgram'

The following object is masked from 'package:lattice':

    panel.fill</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo

Attaching package: 'zoo'

The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gvlma)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="i.-data" class="level1">
<h1>I. Data</h1>
<section id="describe-the-data" class="level2">
<h2 class="anchored" data-anchor-id="describe-the-data">1. Describe the Data:</h2>
<p>When seeking a new home, key factors that influence a purchasing decision include square footage, the number of bedrooms and bathrooms, price, the year of construction, and the number of floors. These variables hold significant importance for prospective homeowners. While this dataset contains additional information, these aforementioned attributes stand out as the most critical. Notably, the data includes house prices, a pivotal factor in evaluating properties. A clear correlation emerges: houses with more bathrooms, bedrooms, and larger square footage tend to command higher prices. With the extensive dataset at hand, thorough analysis can unveil insights into the variables that drive a house’s pricing dynamics.</p>
</section>
<section id="import-the-data" class="level2">
<h2 class="anchored" data-anchor-id="import-the-data">2. Import the Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>house <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"house_32.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(house)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "X"             "id"            "Year"          "Month"        
 [5] "Day"           "day_of_week"   "price"         "bedrooms"     
 [9] "bathrooms"     "sqft_living"   "sqft_lot"      "floors"       
[13] "waterfront"    "view"          "condition"     "grade"        
[17] "sqft_above"    "sqft_basement" "yr_built"      "yr_renovated" 
[21] "zipcode"       "lat"           "long"         </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(<span class="fu">t</span>(<span class="fu">names</span>(house)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1]           
 [1,] "X"            
 [2,] "id"           
 [3,] "Year"         
 [4,] "Month"        
 [5,] "Day"          
 [6,] "day_of_week"  
 [7,] "price"        
 [8,] "bedrooms"     
 [9,] "bathrooms"    
[10,] "sqft_living"  
[11,] "sqft_lot"     
[12,] "floors"       
[13,] "waterfront"   
[14,] "view"         
[15,] "condition"    
[16,] "grade"        
[17,] "sqft_above"   
[18,] "sqft_basement"
[19,] "yr_built"     
[20,] "yr_renovated" 
[21,] "zipcode"      
[22,] "lat"          
[23,] "long"         </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(house)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   15053 obs. of  23 variables:
 $ X            : int  1 2 3 4 5 6 7 8 9 10 ...
 $ id           : num  6.92e+09 2.90e+08 4.12e+09 7.53e+09 2.62e+09 ...
 $ Year         : int  2014 2014 2015 2015 2014 2014 2014 2014 2014 2015 ...
 $ Month        : int  10 6 2 4 9 8 12 10 10 4 ...
 $ Day          : int  27 17 11 21 25 8 23 29 15 16 ...
 $ day_of_week  : int  1 2 3 2 4 5 2 3 3 4 ...
 $ price        : num  610000 675000 1190000 790100 725000 ...
 $ bedrooms     : int  4 6 5 4 3 3 4 3 4 4 ...
 $ bathrooms    : num  2.25 1.75 2.5 2.5 2.5 2.25 2.25 1.75 1.75 2.5 ...
 $ sqft_living  : int  1660 2740 2710 2590 3570 1860 1960 1590 2540 2650 ...
 $ sqft_lot     : int  7350 6360 14989 9341 35271 7200 10400 1322 7200 8685 ...
 $ floors       : num  1 1 1 2 2 1 1 2 1 2 ...
 $ waterfront   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ view         : int  0 3 0 0 0 0 0 0 0 0 ...
 $ condition    : int  3 3 3 3 3 4 4 3 4 3 ...
 $ grade        : int  8 8 8 8 9 7 8 8 7 9 ...
 $ sqft_above   : int  1660 1370 1720 2590 3570 1240 1220 1060 1270 2650 ...
 $ sqft_basement: int  0 1370 990 0 0 620 740 530 1270 0 ...
 $ yr_built     : int  1965 1953 1959 1985 1997 1977 1985 2014 1947 2006 ...
 $ yr_renovated : int  2014 0 0 0 0 0 0 0 0 0 ...
 $ zipcode      : int  98008 98146 98004 98052 98027 98034 98023 98144 98118 98001 ...
 $ lat          : num  47.6 47.5 47.6 47.6 47.5 ...
 $ long         : num  -122 -122 -122 -122 -122 ...</code></pre>
</div>
</div>
</section>
</section>
<section id="ii.-first-model-knn-model" class="level1">
<h1>II. First model: kNN model</h1>
<section id="clean-the-data" class="level2">
<h2 class="anchored" data-anchor-id="clean-the-data">1. Clean the Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(house)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   15053 obs. of  23 variables:
 $ X            : int  1 2 3 4 5 6 7 8 9 10 ...
 $ id           : num  6.92e+09 2.90e+08 4.12e+09 7.53e+09 2.62e+09 ...
 $ Year         : int  2014 2014 2015 2015 2014 2014 2014 2014 2014 2015 ...
 $ Month        : int  10 6 2 4 9 8 12 10 10 4 ...
 $ Day          : int  27 17 11 21 25 8 23 29 15 16 ...
 $ day_of_week  : int  1 2 3 2 4 5 2 3 3 4 ...
 $ price        : num  610000 675000 1190000 790100 725000 ...
 $ bedrooms     : int  4 6 5 4 3 3 4 3 4 4 ...
 $ bathrooms    : num  2.25 1.75 2.5 2.5 2.5 2.25 2.25 1.75 1.75 2.5 ...
 $ sqft_living  : int  1660 2740 2710 2590 3570 1860 1960 1590 2540 2650 ...
 $ sqft_lot     : int  7350 6360 14989 9341 35271 7200 10400 1322 7200 8685 ...
 $ floors       : num  1 1 1 2 2 1 1 2 1 2 ...
 $ waterfront   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ view         : int  0 3 0 0 0 0 0 0 0 0 ...
 $ condition    : int  3 3 3 3 3 4 4 3 4 3 ...
 $ grade        : int  8 8 8 8 9 7 8 8 7 9 ...
 $ sqft_above   : int  1660 1370 1720 2590 3570 1240 1220 1060 1270 2650 ...
 $ sqft_basement: int  0 1370 990 0 0 620 740 530 1270 0 ...
 $ yr_built     : int  1965 1953 1959 1985 1997 1977 1985 2014 1947 2006 ...
 $ yr_renovated : int  2014 0 0 0 0 0 0 0 0 0 ...
 $ zipcode      : int  98008 98146 98004 98052 98027 98034 98023 98144 98118 98001 ...
 $ lat          : num  47.6 47.5 47.6 47.6 47.5 ...
 $ long         : num  -122 -122 -122 -122 -122 ...</code></pre>
</div>
</div>
<section id="remove-the-unnecessary-variables." class="level4">
<h4 class="anchored" data-anchor-id="remove-the-unnecessary-variables.">Remove the unnecessary variables.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># remove unnecesary variables</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>house_1st_model <span class="ot">&lt;-</span> house[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,<span class="dv">14</span>,<span class="dv">19</span><span class="sc">:</span><span class="dv">23</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>house_1st_model <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(house_1st_model)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(<span class="fu">t</span>(<span class="fu">names</span>(house_1st_model)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1]           
 [1,] "price"        
 [2,] "bedrooms"     
 [3,] "bathrooms"    
 [4,] "sqft_living"  
 [5,] "sqft_lot"     
 [6,] "floors"       
 [7,] "waterfront"   
 [8,] "condition"    
 [9,] "grade"        
[10,] "sqft_above"   
[11,] "sqft_basement"</code></pre>
</div>
</div>
</section>
<section id="reorder-the-data-frame." class="level4">
<h4 class="anchored" data-anchor-id="reorder-the-data-frame.">Reorder the data frame.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># reorder the data frame</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>house_1st_model <span class="ot">&lt;-</span> house_1st_model[, <span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">11</span>,<span class="dv">1</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(house_1st_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   15053 obs. of  11 variables:
 $ bedrooms     : int  4 6 5 4 3 3 4 3 4 4 ...
 $ bathrooms    : num  2.25 1.75 2.5 2.5 2.5 2.25 2.25 1.75 1.75 2.5 ...
 $ sqft_living  : int  1660 2740 2710 2590 3570 1860 1960 1590 2540 2650 ...
 $ sqft_lot     : int  7350 6360 14989 9341 35271 7200 10400 1322 7200 8685 ...
 $ floors       : num  1 1 1 2 2 1 1 2 1 2 ...
 $ waterfront   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ condition    : int  3 3 3 3 3 4 4 3 4 3 ...
 $ grade        : int  8 8 8 8 9 7 8 8 7 9 ...
 $ sqft_above   : int  1660 1370 1720 2590 3570 1240 1220 1060 1270 2650 ...
 $ sqft_basement: int  0 1370 990 0 0 620 740 530 1270 0 ...
 $ price        : num  610000 675000 1190000 790100 725000 ...</code></pre>
</div>
</div>
<p>The purpose of the next code is covert the predicted “Price” variable from type: numerical to character and then convert it to factor.</p>
<p>The meaning of the code is:</p>
<ul>
<li><p>The house with “Price” over $500,000 is considered as a High price House</p></li>
<li><p>The house with “Price” below $500,000 is considered as a Low price House</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert the predicted target - Price from numerical to character</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>house_1st_model <span class="ot">&lt;-</span> house_1st_model <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">price =</span> <span class="fu">ifelse</span>(price <span class="sc">&gt;=</span> <span class="dv">500000</span>, <span class="st">"High"</span>, <span class="st">"Low"</span>))</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>house_1st_model<span class="sc">$</span>price <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(house_1st_model<span class="sc">$</span>price)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(house_1st_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  bedrooms bathrooms sqft_living sqft_lot floors waterfront condition grade
1        4      2.25        1660     7350      1          0         3     8
2        6      1.75        2740     6360      1          0         3     8
3        5      2.50        2710    14989      1          0         3     8
4        4      2.50        2590     9341      2          0         3     8
5        3      2.50        3570    35271      2          0         3     9
6        3      2.25        1860     7200      1          0         4     7
  sqft_above sqft_basement price
1       1660             0  High
2       1370          1370  High
3       1720           990  High
4       2590             0  High
5       3570             0  High
6       1240           620   Low</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(house_1st_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   15053 obs. of  11 variables:
 $ bedrooms     : int  4 6 5 4 3 3 4 3 4 4 ...
 $ bathrooms    : num  2.25 1.75 2.5 2.5 2.5 2.25 2.25 1.75 1.75 2.5 ...
 $ sqft_living  : int  1660 2740 2710 2590 3570 1860 1960 1590 2540 2650 ...
 $ sqft_lot     : int  7350 6360 14989 9341 35271 7200 10400 1322 7200 8685 ...
 $ floors       : num  1 1 1 2 2 1 1 2 1 2 ...
 $ waterfront   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ condition    : int  3 3 3 3 3 4 4 3 4 3 ...
 $ grade        : int  8 8 8 8 9 7 8 8 7 9 ...
 $ sqft_above   : int  1660 1370 1720 2590 3570 1240 1220 1060 1270 2650 ...
 $ sqft_basement: int  0 1370 990 0 0 620 740 530 1270 0 ...
 $ price        : Factor w/ 2 levels "High","Low": 1 1 1 1 1 2 2 2 1 2 ...</code></pre>
</div>
</div>
</section>
</section>
<section id="house-test-data" class="level2">
<h2 class="anchored" data-anchor-id="house-test-data">2. House Test Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>house_test <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"house_test_32.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(<span class="fu">t</span>(<span class="fu">names</span>(house_test)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1]           
 [1,] "X"            
 [2,] "id"           
 [3,] "Year"         
 [4,] "Month"        
 [5,] "Day"          
 [6,] "day_of_week"  
 [7,] "bedrooms"     
 [8,] "bathrooms"    
 [9,] "sqft_living"  
[10,] "sqft_lot"     
[11,] "floors"       
[12,] "waterfront"   
[13,] "view"         
[14,] "condition"    
[15,] "grade"        
[16,] "sqft_above"   
[17,] "sqft_basement"
[18,] "yr_built"     
[19,] "yr_renovated" 
[20,] "zipcode"      
[21,] "lat"          
[22,] "long"         </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>house_test_kNN <span class="ot">&lt;-</span> house_test[, <span class="fu">c</span>(<span class="dv">7</span><span class="sc">:</span><span class="dv">12</span>,<span class="dv">14</span><span class="sc">:</span><span class="dv">17</span>)]</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(<span class="fu">t</span>(<span class="fu">names</span>(house_test_kNN)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1]           
 [1,] "bedrooms"     
 [2,] "bathrooms"    
 [3,] "sqft_living"  
 [4,] "sqft_lot"     
 [5,] "floors"       
 [6,] "waterfront"   
 [7,] "condition"    
 [8,] "grade"        
 [9,] "sqft_above"   
[10,] "sqft_basement"</code></pre>
</div>
</div>
</section>
<section id="set-training-and-validation-set" class="level2">
<h2 class="anchored" data-anchor-id="set-training-and-validation-set">3. Set training and validation set</h2>
<p>Here we set our training and validation sets for the KNN Model:</p>
<ul>
<li><p><strong>training_index_kNN</strong> will be the training index for the kNN Model.</p></li>
<li><p><strong>valid_index_kNN</strong> will be the validation index for the kNN Model.</p></li>
<li><p><strong>train_kNN</strong> will be the data frame for the training data for the kNN model after splitting.</p></li>
<li><p><strong>valid_kNN</strong> will be data frame for the validation data for the kNN model after splitting</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">666</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>train_index_kNN <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(house_1st_model), <span class="fl">0.6</span> <span class="sc">*</span> <span class="fu">nrow</span>(house_1st_model))</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>valid_index_kNN <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(house_1st_model), train_index_kNN)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>train_kNN <span class="ot">&lt;-</span> house_1st_model[train_index_kNN, ]</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>valid_kNN <span class="ot">&lt;-</span> house_1st_model[valid_index_kNN, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(train_kNN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9031</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(valid_kNN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6022</code></pre>
</div>
</div>
</section>
<section id="prepare-for-knn-model" class="level2">
<h2 class="anchored" data-anchor-id="prepare-for-knn-model">4. Prepare for kNN model</h2>
<ul>
<li><p><strong>train_norm_kNN</strong> will be the data frame for the normalization of the training data of the kNN model.</p></li>
<li><p><strong>valid_norm_kNN</strong> will be the data frame for the validation of the validation data of the kNN model.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>train_norm_kNN <span class="ot">&lt;-</span> train_kNN</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>valid_norm_kNN <span class="ot">&lt;-</span> valid_kNN</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(<span class="fu">t</span>(<span class="fu">names</span>(train_kNN)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1]           
 [1,] "bedrooms"     
 [2,] "bathrooms"    
 [3,] "sqft_living"  
 [4,] "sqft_lot"     
 [5,] "floors"       
 [6,] "waterfront"   
 [7,] "condition"    
 [8,] "grade"        
 [9,] "sqft_above"   
[10,] "sqft_basement"
[11,] "price"        </code></pre>
</div>
</div>
<p>Normalize Training and Validation set</p>
<p>Here we will prepare the data for analysis by creating pre-process model. We also normalized the selected columns in the train_norm data set based on the transformations learned from the norm values model.</p>
<ul>
<li><strong>norm_values_kNN</strong> will be the data frame that will prepare for the analysis for the kNN model.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>norm_value_kNN <span class="ot">&lt;-</span> <span class="fu">preProcess</span>(train_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)],</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"center"</span>,</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"scale"</span>))</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>train_norm_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)] <span class="ot">&lt;-</span> <span class="fu">predict</span>(norm_value_kNN, </span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>                                    train_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)]) </span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(train_norm_kNN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        bedrooms  bathrooms sqft_living    sqft_lot     floors  waterfront
1598  -0.3938457  0.5071726   0.6599165 -0.24900339  0.9220151 -0.09571844
12926  0.6941997  1.1602849  -0.1750038 -0.07784875 -0.9175339 -0.09571844
14944 -0.3938457  0.5071726  -0.5219837 -0.19031638  0.9220151 -0.09571844
13195 -1.4818911 -1.4521641  -1.1183554  9.19747202 -0.9175339 -0.09571844
7291  -0.3938457  0.5071726  -0.3268076 -0.32797961  2.7615641 -0.09571844
14990 -1.4818911 -1.4521641  -1.3677472 -0.24803160 -0.9175339 -0.09571844
       condition      grade sqft_above sqft_basement price
1598  -0.6342663 -0.5647946  1.0736646    -0.6545079  High
12926 -0.6342663 -0.5647946  0.1513682    -0.6545079   Low
14944 -2.1641966 -0.5647946 -0.2319238    -0.6545079   Low
13195  2.4255943 -1.4170353 -0.8907069    -0.6545079   Low
7291  -0.6342663  0.2874460 -0.2319238    -0.2451126  High
14990  2.4255943 -1.4170353 -1.1661981    -0.6545079   Low</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>valid_norm_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)] <span class="ot">&lt;-</span> <span class="fu">predict</span>(norm_value_kNN,</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>                                    valid_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)])</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(valid_norm_kNN)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     bedrooms  bathrooms sqft_living    sqft_lot     floors  waterfront
1   0.6941997  0.1806165  -0.4569250 -0.18901276 -0.9175339 -0.09571844
3   1.7822451  0.5071726   0.6816027 -0.00795053 -0.9175339 -0.09571844
5  -0.3938457  0.5071726   1.6141112  0.47278046  0.9220151 -0.09571844
6  -0.3938457  0.1806165  -0.2400626 -0.19256811 -0.9175339 -0.09571844
9   0.6941997 -0.4724957   0.4972697 -0.19256811 -0.9175339 -0.09571844
10  0.6941997  0.5071726   0.6165440 -0.15737012  0.9220151 -0.09571844
    condition      grade  sqft_above sqft_basement price
1  -0.6342663  0.2874460 -0.16005656    -0.6545079  High
3  -0.6342663  0.2874460 -0.08818931     1.5971664  High
5  -0.6342663  1.1396867  2.12771759    -0.6545079  High
6   0.8956640 -0.5647946 -0.66312732     0.7556315   Low
9   0.8956640 -0.5647946 -0.62719369     2.2340035  High
10 -0.6342663  1.1396867  1.02575308    -0.6545079   Low</code></pre>
</div>
</div>
<p>Normalize house test data for kNN model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>house_test_kNN_norm <span class="ot">&lt;-</span> <span class="fu">predict</span>(norm_value_kNN, house_test_kNN)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>house_test_kNN_norm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     bedrooms  bathrooms sqft_living    sqft_lot      floors  waterfront
1   0.6941997 -0.7990518  0.24787789 -0.04798379 -0.91753388 -0.09571844
2  -1.4818911 -0.1459396 -0.43523876 -0.21641267 -0.91753388 -0.09571844
3  -0.3938457  0.1806165 -0.28343506  2.00113147 -0.91753388 -0.09571844
4  -0.3938457  0.5071726  0.09607419 -0.28737749  0.00224062 -0.09571844
5   1.7822451  1.4868410  1.02858263  0.12139318  0.92201512 -0.09571844
6   0.6941997 -0.4724957 -0.39186628 -0.29093285  0.00224062 -0.09571844
7  -1.4818911 -1.4521641 -1.53039403 -0.30738227 -0.91753388 -0.09571844
8   0.6941997  0.5071726  0.52979904 -0.17694826  0.92201512 -0.09571844
9  -0.3938457  0.5071726 -0.30512131 -0.10169331  0.92201512 -0.09571844
10 -0.3938457  0.5071726 -0.38102316 -0.26637721  0.92201512 -0.09571844
11 -0.3938457  0.1806165 -0.63041495 -0.17123600 -0.91753388 -0.09571844
12  0.6941997 -0.1459396  0.12860355 -0.29069582 -0.91753388 -0.09571844
13 -1.4818911 -1.4521641 -0.90149299 -0.25518971 -0.91753388 -0.09571844
14 -0.3938457  0.1806165  0.38883847 -0.13357297 -0.91753388 -0.09571844
15 -0.3938457  0.8337288 -0.26174882  1.25988799 -0.91753388 -0.09571844
16  1.7822451  2.1399533  1.92856171 -0.19965511  0.92201512 -0.09571844
17 -0.3938457  0.1806165 -0.34849379 -0.25564005  0.92201512 -0.09571844
18 -0.3938457 -0.4724957 -0.70631680 -0.13212712 -0.91753388 -0.09571844
19 -1.4818911 -1.4521641 -1.47617842 -0.09301825 -0.91753388 -0.09571844
20  0.6941997  0.5071726  1.10448448 -0.17818078  0.92201512 -0.09571844
    condition      grade  sqft_above sqft_basement
1  -0.6342663 -0.5647946  0.11543457   0.300747833
2  -0.6342663  0.2874460 -0.13610081  -0.654507925
3   0.8956640 -0.5647946  0.03158944  -0.654507925
4   2.4255943 -0.5647946 -0.61521582   1.369724513
5  -0.6342663  1.1396867  0.40290357   1.392468698
6   2.4255943 -0.5647946 -0.90268482   0.892096635
7   2.4255943 -1.4170353 -1.34586620  -0.654507925
8  -0.6342663  0.2874460  0.92993007  -0.654507925
9   0.8956640  0.2874460  0.00763369  -0.654507925
10 -0.6342663  0.2874460 -0.07621144  -0.654507925
11 -0.6342663 -0.5647946 -0.69906094   0.005073432
12 -0.6342663 -0.5647946 -0.83081757   1.847352392
13 -0.6342663 -0.5647946 -0.65114944  -0.654507925
14  0.8956640  0.2874460  0.04356732   0.732887342
15 -0.6342663  0.2874460 -0.54334857   0.482701310
16 -0.6342663 -0.5647946  2.47507597  -0.654507925
17 -0.6342663  0.2874460 -0.04027781  -0.654507925
18  2.4255943 -0.5647946 -0.43554769  -0.654507925
19  2.4255943 -1.4170353 -1.28597682  -0.654507925
20 -0.6342663  1.1396867  1.56475746  -0.654507925</code></pre>
</div>
</div>
</section>
<section id="knn-model" class="level2">
<h2 class="anchored" data-anchor-id="knn-model">5. kNN model</h2>
<section id="k-3" class="level3">
<h3 class="anchored" data-anchor-id="k-3">5.1 k = 3</h3>
<section id="the-training" class="level4">
<h4 class="anchored" data-anchor-id="the-training">The Training</h4>
<ul>
<li><strong>kNN_model_k3</strong> is the kNN model for k = 3.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>kNN_model_k3 <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">knn3</span>(price <span class="sc">~</span>., <span class="at">data =</span> train_norm_kNN, <span class="at">k =</span> <span class="dv">3</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>kNN_model_k3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3-nearest neighbor model
Training set outcome distribution:

High  Low 
3881 5150 </code></pre>
</div>
</div>
</section>
<section id="the-prediction" class="level4">
<h4 class="anchored" data-anchor-id="the-prediction">The Prediction</h4>
</section>
<section id="prediction-on-training-set" class="level4">
<h4 class="anchored" data-anchor-id="prediction-on-training-set">Prediction on Training set</h4>
<ul>
<li><strong>kNN_pred_k3_train</strong> will be the prediction for the training set for the kNN model for k = 3.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>kNN_pred_k3_train <span class="ot">&lt;-</span> <span class="fu">predict</span>(kNN_model_k3, <span class="at">newdata =</span> train_norm_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)],</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kNN_pred_k3_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Low  Low  Low  Low  High Low 
Levels: High Low</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(kNN_pred_k3_train, <span class="fu">as.factor</span>(train_norm_kNN[, <span class="dv">11</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction High  Low
      High 3139  526
      Low   742 4624
                                          
               Accuracy : 0.8596          
                 95% CI : (0.8523, 0.8667)
    No Information Rate : 0.5703          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.7116          
                                          
 Mcnemar's Test P-Value : 1.562e-09       
                                          
            Sensitivity : 0.8088          
            Specificity : 0.8979          
         Pos Pred Value : 0.8565          
         Neg Pred Value : 0.8617          
             Prevalence : 0.4297          
         Detection Rate : 0.3476          
   Detection Prevalence : 0.4058          
      Balanced Accuracy : 0.8533          
                                          
       'Positive' Class : High            
                                          </code></pre>
</div>
</div>
</section>
<section id="prediction-on-validation-set" class="level4">
<h4 class="anchored" data-anchor-id="prediction-on-validation-set">Prediction on Validation set</h4>
<ul>
<li><strong>kNN_pred_k3_valid</strong> will be the prediction for the validation set for the kNN model for k = 3.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>kNN_pred_k3_valid <span class="ot">&lt;-</span> <span class="fu">predict</span>(kNN_model_k3, <span class="at">newdata =</span> valid_norm_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)],</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kNN_pred_k3_valid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Low  High High Low  Low  High
Levels: High Low</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>kNN_pred_k3_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(kNN_model_k3, <span class="at">newdata =</span> valid_norm_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)],</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">"prob"</span>)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kNN_pred_k3_prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          High       Low
[1,] 0.3333333 0.6666667
[2,] 0.6666667 0.3333333
[3,] 0.6666667 0.3333333
[4,] 0.3333333 0.6666667
[5,] 0.3333333 0.6666667
[6,] 0.6666667 0.3333333</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(kNN_pred_k3_valid, <span class="fu">as.factor</span>(valid_norm_kNN[, <span class="dv">11</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction High  Low
      High 1765  628
      Low   789 2840
                                          
               Accuracy : 0.7647          
                 95% CI : (0.7538, 0.7754)
    No Information Rate : 0.5759          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.5143          
                                          
 Mcnemar's Test P-Value : 2.133e-05       
                                          
            Sensitivity : 0.6911          
            Specificity : 0.8189          
         Pos Pred Value : 0.7376          
         Neg Pred Value : 0.7826          
             Prevalence : 0.4241          
         Detection Rate : 0.2931          
   Detection Prevalence : 0.3974          
      Balanced Accuracy : 0.7550          
                                          
       'Positive' Class : High            
                                          </code></pre>
</div>
</div>
</section>
<section id="accuracy-comparison" class="level4">
<h4 class="anchored" data-anchor-id="accuracy-comparison">Accuracy comparison:</h4>
<p>Training: 0.8596 = 85.96%</p>
<p>Validation: 0.7647 = 76.47%</p>
</section>
</section>
<section id="k-5" class="level3">
<h3 class="anchored" data-anchor-id="k-5">5.2 k = 5</h3>
<section id="the-training-1" class="level4">
<h4 class="anchored" data-anchor-id="the-training-1">The Training</h4>
<ul>
<li><strong>kNN_model_k5</strong> is kNN model for k = 5.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>kNN_model_k5 <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">knn3</span>(price <span class="sc">~</span>., <span class="at">data =</span> train_norm_kNN, <span class="at">k =</span> <span class="dv">5</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>kNN_model_k5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>5-nearest neighbor model
Training set outcome distribution:

High  Low 
3881 5150 </code></pre>
</div>
</div>
</section>
<section id="the-prediction-1" class="level4">
<h4 class="anchored" data-anchor-id="the-prediction-1">The Prediction</h4>
</section>
<section id="prediction-on-training-set-1" class="level4">
<h4 class="anchored" data-anchor-id="prediction-on-training-set-1">Prediction on Training Set</h4>
<ul>
<li><strong>kNN_pred_k5_train</strong> is the prediction for the training set for the kNN model for k = 5.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>kNN_pred_k5_train <span class="ot">&lt;-</span> <span class="fu">predict</span>(kNN_model_k5, <span class="at">newdata =</span> train_norm_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)],</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kNN_pred_k5_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Low  Low  Low  Low  High Low 
Levels: High Low</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(kNN_pred_k5_train, <span class="fu">as.factor</span>(train_norm_kNN[, <span class="dv">11</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction High  Low
      High 3016  615
      Low   865 4535
                                          
               Accuracy : 0.8361          
                 95% CI : (0.8283, 0.8437)
    No Information Rate : 0.5703          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.663           
                                          
 Mcnemar's Test P-Value : 9.643e-11       
                                          
            Sensitivity : 0.7771          
            Specificity : 0.8806          
         Pos Pred Value : 0.8306          
         Neg Pred Value : 0.8398          
             Prevalence : 0.4297          
         Detection Rate : 0.3340          
   Detection Prevalence : 0.4021          
      Balanced Accuracy : 0.8289          
                                          
       'Positive' Class : High            
                                          </code></pre>
</div>
</div>
</section>
<section id="prediction-on-validation-set-1" class="level4">
<h4 class="anchored" data-anchor-id="prediction-on-validation-set-1">Prediction on Validation Set</h4>
<ul>
<li><strong>kNN_pred_k5_valid</strong> is the prediction for the validation set for the kNN model for k = 5.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>kNN_pred_k5_valid <span class="ot">&lt;-</span> <span class="fu">predict</span>(kNN_model_k5, <span class="at">newdata =</span> valid_norm_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)],</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kNN_pred_k5_valid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] High High High Low  Low  High
Levels: High Low</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>kNN_pred_k5_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(kNN_model_k5, <span class="at">newdata =</span> valid_norm_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)],</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">"prob"</span>)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kNN_pred_k5_prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     High Low
[1,]  0.6 0.4
[2,]  0.8 0.2
[3,]  0.6 0.4
[4,]  0.2 0.8
[5,]  0.4 0.6
[6,]  0.6 0.4</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(kNN_pred_k5_valid, <span class="fu">as.factor</span>(valid_norm_kNN[, <span class="dv">11</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction High  Low
      High 1768  564
      Low   786 2904
                                          
               Accuracy : 0.7758          
                 95% CI : (0.7651, 0.7863)
    No Information Rate : 0.5759          
    P-Value [Acc &gt; NIR] : &lt; 2e-16         
                                          
                  Kappa : 0.5358          
                                          
 Mcnemar's Test P-Value : 1.8e-09         
                                          
            Sensitivity : 0.6922          
            Specificity : 0.8374          
         Pos Pred Value : 0.7581          
         Neg Pred Value : 0.7870          
             Prevalence : 0.4241          
         Detection Rate : 0.2936          
   Detection Prevalence : 0.3872          
      Balanced Accuracy : 0.7648          
                                          
       'Positive' Class : High            
                                          </code></pre>
</div>
</div>
</section>
<section id="accuracy-comparison-1" class="level4">
<h4 class="anchored" data-anchor-id="accuracy-comparison-1">Accuracy Comparison:</h4>
<p>Training: 0.8362 = 83.62%</p>
<p>Validation: 0.776 = 77.6%</p>
</section>
</section>
<section id="k-9" class="level3">
<h3 class="anchored" data-anchor-id="k-9">5.3 k = 9</h3>
<section id="the-training-2" class="level4">
<h4 class="anchored" data-anchor-id="the-training-2">The Training</h4>
<ul>
<li>kNN_model_k9 is kNN model for k=9.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>kNN_model_k9 <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">knn3</span>(price <span class="sc">~</span>., <span class="at">data =</span> train_norm_kNN, <span class="at">k =</span> <span class="dv">9</span>)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>kNN_model_k9</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>9-nearest neighbor model
Training set outcome distribution:

High  Low 
3881 5150 </code></pre>
</div>
</div>
</section>
<section id="the-prediction-2" class="level4">
<h4 class="anchored" data-anchor-id="the-prediction-2">The Prediction</h4>
</section>
<section id="prediction-on-training-set-2" class="level4">
<h4 class="anchored" data-anchor-id="prediction-on-training-set-2">Prediction on Training Set</h4>
<ul>
<li>kNN_pred_k9_train is the prediction for the training set for the kNN model for k=5.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>kNN_pred_k9_train <span class="ot">&lt;-</span> <span class="fu">predict</span>(kNN_model_k9, <span class="at">newdata =</span> train_norm_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)],</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kNN_pred_k9_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Low Low Low Low Low Low
Levels: High Low</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(kNN_pred_k9_train, <span class="fu">as.factor</span>(train_norm_kNN[,<span class="dv">11</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction High  Low
      High 2888  647
      Low   993 4503
                                          
               Accuracy : 0.8184          
                 95% CI : (0.8103, 0.8263)
    No Information Rate : 0.5703          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.6254          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 0.7441          
            Specificity : 0.8744          
         Pos Pred Value : 0.8170          
         Neg Pred Value : 0.8193          
             Prevalence : 0.4297          
         Detection Rate : 0.3198          
   Detection Prevalence : 0.3914          
      Balanced Accuracy : 0.8093          
                                          
       'Positive' Class : High            
                                          </code></pre>
</div>
</div>
</section>
<section id="prediction-on-validation-set-2" class="level4">
<h4 class="anchored" data-anchor-id="prediction-on-validation-set-2">Prediction on Validation Set</h4>
<ul>
<li>kNN_pred_k9_valid is the prediction for the validation set for the kNN model for k = 5.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>kNN_pred_k9_valid <span class="ot">&lt;-</span> <span class="fu">predict</span>(kNN_model_k9, <span class="at">newdata =</span> valid_norm_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)],</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kNN_pred_k9_valid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Low  High High Low  High Low 
Levels: High Low</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>kNN_pred_k9_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(kNN_model_k9, <span class="at">newdata =</span> valid_norm_kNN[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">11</span>)],</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">type =</span> <span class="st">"prob"</span>)</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kNN_pred_k9_prob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          High       Low
[1,] 0.3333333 0.6666667
[2,] 0.7777778 0.2222222
[3,] 0.7777778 0.2222222
[4,] 0.2222222 0.7777778
[5,] 0.5555556 0.4444444
[6,] 0.4444444 0.5555556</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(kNN_pred_k9_valid, <span class="fu">as.factor</span>(valid_norm_kNN[,<span class="dv">11</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction High  Low
      High 1767  547
      Low   787 2921
                                          
               Accuracy : 0.7785          
                 95% CI : (0.7678, 0.7889)
    No Information Rate : 0.5759          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.5408          
                                          
 Mcnemar's Test P-Value : 6.004e-11       
                                          
            Sensitivity : 0.6919          
            Specificity : 0.8423          
         Pos Pred Value : 0.7636          
         Neg Pred Value : 0.7878          
             Prevalence : 0.4241          
         Detection Rate : 0.2934          
   Detection Prevalence : 0.3843          
      Balanced Accuracy : 0.7671          
                                          
       'Positive' Class : High            
                                          </code></pre>
</div>
</div>
</section>
<section id="accuracy-comparison-2" class="level4">
<h4 class="anchored" data-anchor-id="accuracy-comparison-2">Accuracy Comparison:</h4>
<p>Training: 0.8182 = 81.82%</p>
<p>Validation: 0.7783 = 77.83%</p>
</section>
</section>
<section id="model-evaluation" class="level3">
<h3 class="anchored" data-anchor-id="model-evaluation">5.4 Model Evaluation</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="k-3-1" class="level4">
<h4 class="anchored" data-anchor-id="k-3-1">k = 3</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>ROSE<span class="sc">::</span><span class="fu">roc.curve</span>(valid_norm_kNN<span class="sc">$</span>price, kNN_pred_k3_valid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project-2_Final_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve (AUC): 0.755</code></pre>
</div>
</div>
</section>
<section id="k-5-1" class="level4">
<h4 class="anchored" data-anchor-id="k-5-1">k = 5</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>ROSE<span class="sc">::</span><span class="fu">roc.curve</span>(valid_norm_kNN<span class="sc">$</span>price, kNN_pred_k5_valid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project-2_Final_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve (AUC): 0.765</code></pre>
</div>
</div>
</section>
<section id="k-9-1" class="level4">
<h4 class="anchored" data-anchor-id="k-9-1">k = 9</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>ROSE<span class="sc">::</span><span class="fu">roc.curve</span>(valid_norm_kNN<span class="sc">$</span>price, kNN_pred_k9_valid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project-2_Final_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Area under the curve (AUC): 0.767</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="conclusion-for-the-best-knn-model" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-for-the-best-knn-model">6. Conclusion for the best kNN model</h2>
<section id="accuracy-comparison-3" class="level3">
<h3 class="anchored" data-anchor-id="accuracy-comparison-3">6.1 Accuracy Comparison</h3>
<ul>
<li><p>k = 3:</p>
<ul>
<li><p>Training Set: 0.8596 = 85.96%</p>
<p>Validation Set: 0.7647 = 76.47%</p></li>
</ul></li>
<li><p>k = 5</p>
<ul>
<li><p>Training Set: 0.8362 = 83.62%</p>
<p>Validation Set: 0.776 = 77.6%</p></li>
</ul></li>
<li><p>k = 9</p>
<ul>
<li><p>Training Set: 0.8182 = 81.82%</p>
<p>Validation Set: 0.7783 = 77.83%</p></li>
<li><p>This kNN model with k = 9 have the Accuracy between Training and Validation set has the smallest difference</p></li>
</ul></li>
</ul>
</section>
<section id="auc-comparison" class="level3">
<h3 class="anchored" data-anchor-id="auc-comparison">6.2 AUC Comparison</h3>
<ul>
<li><p>k = 3: AUC = 0.755</p></li>
<li><p>k = 5: AUC = 0.765</p></li>
<li><p>k = 9: AUC = 0.767</p></li>
</ul>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">6.3 Conclusion:</h3>
<ul>
<li><p>As we can see, the Accuracy between Training and Validation set and AUC of k =9 is the best out of 3 models, because:</p>
<ul>
<li><p>kNN model with k = 9 have the Accuracy between Training and Validation set has the smallest difference</p></li>
<li><p>AUC of kNN model have the largest number out of 3 (0.767 &gt; 0.765 &gt; 0.755)</p></li>
</ul></li>
</ul>
</section>
</section>
</section>
<section id="iii.-decision-tree-and-multiple-regression-model" class="level1">
<h1>III. Decision Tree and Multiple Regression Model</h1>
<section id="regression-tree-model" class="level2">
<h2 class="anchored" data-anchor-id="regression-tree-model">1. Regression Tree Model</h2>
<section id="clean-the-data-1" class="level3">
<h3 class="anchored" data-anchor-id="clean-the-data-1">1.1 Clean The Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>house2 <span class="ot">&lt;-</span> house[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">17</span><span class="sc">:</span><span class="dv">18</span>, <span class="dv">21</span><span class="sc">:</span><span class="dv">23</span>)]</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(house2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   15053 obs. of  12 variables:
 $ price       : num  610000 675000 1190000 790100 725000 ...
 $ bedrooms    : int  4 6 5 4 3 3 4 3 4 4 ...
 $ bathrooms   : num  2.25 1.75 2.5 2.5 2.5 2.25 2.25 1.75 1.75 2.5 ...
 $ sqft_living : int  1660 2740 2710 2590 3570 1860 1960 1590 2540 2650 ...
 $ sqft_lot    : int  7350 6360 14989 9341 35271 7200 10400 1322 7200 8685 ...
 $ floors      : num  1 1 1 2 2 1 1 2 1 2 ...
 $ waterfront  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ view        : int  0 3 0 0 0 0 0 0 0 0 ...
 $ condition   : int  3 3 3 3 3 4 4 3 4 3 ...
 $ grade       : int  8 8 8 8 9 7 8 8 7 9 ...
 $ yr_built    : int  1965 1953 1959 1985 1997 1977 1985 2014 1947 2006 ...
 $ yr_renovated: int  2014 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(house2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    price bedrooms bathrooms sqft_living sqft_lot floors waterfront view
1  610000        4      2.25        1660     7350      1          0    0
2  675000        6      1.75        2740     6360      1          0    3
3 1190000        5      2.50        2710    14989      1          0    0
4  790100        4      2.50        2590     9341      2          0    0
5  725000        3      2.50        3570    35271      2          0    0
6  445000        3      2.25        1860     7200      1          0    0
  condition grade yr_built yr_renovated
1         3     8     1965         2014
2         3     8     1953            0
3         3     8     1959            0
4         3     8     1985            0
5         3     9     1997            0
6         4     7     1977            0</code></pre>
</div>
</div>
</section>
<section id="training-and-validation-of-regression-tree" class="level3">
<h3 class="anchored" data-anchor-id="training-and-validation-of-regression-tree">1.2 Training and Validation of Regression Tree</h3>
<ul>
<li><p>train_index_class_tr will be the training index</p></li>
<li><p>valid_index_class_tr will be the validation index</p></li>
<li><p>train_class will be the data frame for the training data</p></li>
<li><p>valid_class will be the data frame for the validation data</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">666</span>)</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>train_index_class_tr <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(house2), <span class="fl">0.7</span> <span class="sc">*</span> <span class="fu">nrow</span>(house2))</span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a>valid_index_class_tr <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(house2), train_index_class_tr)</span>
<span id="cb106-5"><a href="#cb106-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-6"><a href="#cb106-6" aria-hidden="true" tabindex="-1"></a>train_class <span class="ot">&lt;-</span> house2[train_index_class_tr,]</span>
<span id="cb106-7"><a href="#cb106-7" aria-hidden="true" tabindex="-1"></a>valid_class <span class="ot">&lt;-</span> house2[valid_index_class_tr,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(train_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10537</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(valid_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4516</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(train_class, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       price bedrooms bathrooms sqft_living sqft_lot floors waterfront view
1598  555000        3      2.50        2690     4819    2.0          0    0
12926 330000        4      3.00        1920    12040    1.0          0    0
14944 205000        3      2.50        1600     7295    2.0          0    0
13195 474000        2      1.00        1050   403365    1.0          0    3
7291  586500        3      2.50        1780     1487    3.0          0    0
14990 207000        2      1.00         820     4860    1.0          0    0
873   364808        3      1.75        2320     7875    1.0          0    0
652   496800        4      2.25        1850     2340    2.5          0    0
1697  585000        4      2.50        2630     6185    2.0          0    0
1074  445000        3      1.00        1050     5664    1.0          0    0
      condition grade yr_built yr_renovated
1598          3     7     2004            0
12926         3     7     1962            0
14944         2     7     1993            0
13195         5     6     1905            0
7291          3     8     2006            0
14990         5     6     1955            0
873           3     8     1967            0
652           3     8     2014            0
1697          3     9     1999            0
1074          4     7     1947            0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(valid_class, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     price bedrooms bathrooms sqft_living sqft_lot floors waterfront view
3  1190000        5      2.50        2710    14989    1.0          0    0
6   445000        3      2.25        1860     7200    1.0          0    0
9   525000        4      1.75        2540     7200    1.0          0    0
10  424000        4      2.50        2650     8685    2.0          0    0
12  397000        4      1.75        2020     6000    1.0          0    0
15  625000        3      1.75        2100     3264    1.5          0    0
19  306000        3      1.00         910     8658    1.0          0    0
21  287500        4      2.00        1220     9147    1.0          0    0
32  571000        4      1.00        1350     4000    1.5          0    0
42  499900        4      3.00        2180    12196    2.0          0    0
   condition grade yr_built yr_renovated
3          3     8     1959            0
6          4     7     1977            0
9          4     7     1947            0
10         3     9     2006            0
12         3     7     1959            0
15         5     7     1912            0
19         3     7     1955            0
21         5     7     1953            0
32         3     8     1930            0
42         4     7     1968            0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(train_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   10537 obs. of  12 variables:
 $ price       : num  555000 330000 205000 474000 586500 ...
 $ bedrooms    : int  3 4 3 2 3 2 3 4 4 3 ...
 $ bathrooms   : num  2.5 3 2.5 1 2.5 1 1.75 2.25 2.5 1 ...
 $ sqft_living : int  2690 1920 1600 1050 1780 820 2320 1850 2630 1050 ...
 $ sqft_lot    : int  4819 12040 7295 403365 1487 4860 7875 2340 6185 5664 ...
 $ floors      : num  2 1 2 1 3 1 1 2.5 2 1 ...
 $ waterfront  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ view        : int  0 0 0 3 0 0 0 0 0 0 ...
 $ condition   : int  3 3 2 5 3 5 3 3 3 4 ...
 $ grade       : int  7 7 7 6 8 6 8 8 9 7 ...
 $ yr_built    : int  2004 1962 1993 1905 2006 1955 1967 2014 1999 1947 ...
 $ yr_renovated: int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(valid_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   4516 obs. of  12 variables:
 $ price       : num  1190000 445000 525000 424000 397000 ...
 $ bedrooms    : int  5 3 4 4 4 3 3 4 4 4 ...
 $ bathrooms   : num  2.5 2.25 1.75 2.5 1.75 1.75 1 2 1 3 ...
 $ sqft_living : int  2710 1860 2540 2650 2020 2100 910 1220 1350 2180 ...
 $ sqft_lot    : int  14989 7200 7200 8685 6000 3264 8658 9147 4000 12196 ...
 $ floors      : num  1 1 1 2 1 1.5 1 1 1.5 2 ...
 $ waterfront  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ view        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ condition   : int  3 4 4 3 3 5 3 5 3 4 ...
 $ grade       : int  8 7 7 9 7 7 7 7 8 7 ...
 $ yr_built    : int  1959 1977 1947 2006 1959 1912 1955 1953 1930 1968 ...
 $ yr_renovated: int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
</section>
<section id="correlation-between-variables" class="level3">
<h3 class="anchored" data-anchor-id="correlation-between-variables">1.3 Correlation Between Variables</h3>
<p>In this instance, we will employ the corrgram library to gain insights into the correlations among our variables. The color blue signifies a positive correlation, whereas red indicates a negative one. The intensity or depth of the color reflects the strength of the relationship. A darker shade suggests a more robust correlation, whether it is positive or negative.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrgram</span>(train_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project-2_Final_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="regression-tree" class="level3">
<h3 class="anchored" data-anchor-id="regression-tree">1.4 Regression Tree</h3>
<p>Next we will create a regression tree to use as a prediction model and help us with our final decision.</p>
<p>I have created a decision tree model and we can see that sqft_liv and grade are 2 important aspect to determine the price of the house. Moreover, different variable we could use to determine the price of the house that could be on this project is waterfront and yr_built. We could use these variable, including sqft_liv to determine if the price of the house is high or low.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>regress_tr <span class="ot">&lt;-</span> <span class="fu">rpart</span>(price <span class="sc">~</span> .,</span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> train_class, <span class="at">method =</span> <span class="st">"anova"</span>, <span class="at">maxdepth =</span> <span class="dv">20</span>)</span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prp</span>(regress_tr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project-2_Final_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comparing-the-training-set-and-validation-set-of-decision-tree-model" class="level3">
<h3 class="anchored" data-anchor-id="comparing-the-training-set-and-validation-set-of-decision-tree-model">1.5 Comparing the training set and validation set of decision tree model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>pred_train <span class="ot">&lt;-</span> <span class="fu">predict</span>(regress_tr, train_class)</span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(pred_train, train_class<span class="sc">$</span>price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    ME     RMSE      MAE       MPE     MAPE
Test set -1.365306e-11 233236.1 156152.6 -14.86529 33.79236</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>pred_valid <span class="ot">&lt;-</span> <span class="fu">predict</span>(regress_tr, valid_class)</span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(pred_valid, valid_class<span class="sc">$</span>price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                ME     RMSE      MAE       MPE     MAPE
Test set -2763.554 244315.5 160821.9 -15.23141 34.39402</code></pre>
</div>
</div>
<p>In assessing the performance of our multiple regression model across both the training and validation sets, we rely on the Root Mean Square Deviation (RMSE) as our primary metric. The RMSE is a pivotal measure for gauging the accuracy of our model, with lower values signifying higher accuracy. In the case of our regression tree model, the RMSE for the training set is recorded at 233236.1 while the validation set shows a slightly higher RMSE of 244315.5.</p>
<p>Since the RMSE is an indicator of error, the relative discrepancy between these values suggests that the validation set is more accurate compared to the training set. This discrepancy is within expectations, considering that training models typically outperform validation models due to the larger volume of data available for training.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(house2<span class="sc">$</span>price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 367712.6</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(train_class<span class="sc">$</span>price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 372411.9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(valid_class<span class="sc">$</span>price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 356538.6</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(train_class<span class="sc">$</span>price) <span class="sc">-</span> <span class="fu">min</span>(train_class<span class="sc">$</span>price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7619000</code></pre>
</div>
</div>
</section>
</section>
<section id="multiple-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-model">2. Multiple Regression Model</h2>
<p>In order to understand the data overall, we decided to create a regression model which contains all of the variables we initially decided on. Here, it seems that the adjusted R-squared is, 0.6547, which implies that 65.47% of the variance in the price of a home can be explained by the set of independent variables. In addition, the adjustment considers the number of variables in the model.</p>
<p>Further examining the variables, it seems that many of them are quite significant to the model including bedrooms, bathrooms, and sqft_living. On the other hand, the floors variable is not significant.</p>
<p>In this case, the intercept of 7.416e+04 (approx. $741,600) could be identified as the average price for housing in the King County.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>house32_new <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> bedrooms <span class="sc">+</span> </span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>                    bathrooms <span class="sc">+</span></span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a>                    sqft_living <span class="sc">+</span> </span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a>                    sqft_lot <span class="sc">+</span></span>
<span id="cb133-5"><a href="#cb133-5" aria-hidden="true" tabindex="-1"></a>                    waterfront, <span class="at">data =</span> train_class)</span>
<span id="cb133-6"><a href="#cb133-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(house32_new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ bedrooms + bathrooms + sqft_living + sqft_lot + 
    waterfront, data = train_class)

Residuals:
     Min       1Q   Median       3Q      Max 
-1266327  -140670   -17732   106581  4159055 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  7.416e+04  9.769e+03   7.591 3.44e-14 ***
bedrooms    -5.896e+04  3.371e+03 -17.489  &lt; 2e-16 ***
bathrooms    7.147e+03  4.896e+03   1.460    0.144    
sqft_living  3.132e+02  4.422e+00  70.823  &lt; 2e-16 ***
sqft_lot    -3.864e-01  6.205e-02  -6.226 4.96e-10 ***
waterfront   6.852e+05  2.618e+04  26.173  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 250200 on 10531 degrees of freedom
Multiple R-squared:  0.5488,    Adjusted R-squared:  0.5486 
F-statistic:  2562 on 5 and 10531 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In this instance, we will employ the corrgram library to gain insights the correlations among our variables. The color blue signifies a positive correlation, whereas red indicates a negative one. The intensity or depth of the color reflects the strength of the relationship. A darker shade suggests a more robust correlation, whether it is positive or negative.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrgram)</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(price <span class="sc">~</span> ., <span class="at">data =</span> train_class, <span class="at">pch =</span> <span class="st">"."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project-2_Final_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrgram</span>(train_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Project-2_Final_files/figure-html/unnamed-chunk-62-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(house32_new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   bedrooms   bathrooms sqft_living    sqft_lot  waterfront 
   1.599086    2.372012    2.770475    1.048785    1.019953 </code></pre>
</div>
</div>
<section id="evaluate-and-comparing-the-accuracy-of-training-set-and-validation-set" class="level3">
<h3 class="anchored" data-anchor-id="evaluate-and-comparing-the-accuracy-of-training-set-and-validation-set">2.1 Evaluate and Comparing the accuracy of training set and validation set</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a>house32_pred_train <span class="ot">&lt;-</span> <span class="fu">predict</span>(house32_new,</span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a>                                train_class)</span>
<span id="cb139-3"><a href="#cb139-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb139-4"><a href="#cb139-4" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(house32_pred_train, train_class<span class="sc">$</span>price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    ME     RMSE      MAE       MPE     MAPE
Test set -2.919012e-08 250141.8 168566.3 -12.74722 34.97669</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a>house32_pred_valid <span class="ot">&lt;-</span> <span class="fu">predict</span>(house32_new,</span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>                                valid_class)</span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(house32_pred_valid, valid_class<span class="sc">$</span>price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                ME     RMSE      MAE       MPE     MAPE
Test set -22.10126 246679.3 168629.6 -12.22318 34.98596</code></pre>
</div>
</div>
<p>In assessing the performance of our multiple regression model across both the training and validation sets, we rely on the Root Mean Square Deviation (RMSE) as our primary metric. The RMSE is a pivotal measure for gauging the accuracy of our model, with lower values signifying higher accuracy.</p>
<p>In the case of our multiple linear regression, the RMSE for the training set is recorded at 218823.3 while the validation set shows a slightly higher RMSE of 211200.6. Since the RMSE is an indicator of error, the relative discrepancy between these values suggests that the validation set is less accurate compared to the training set. This discrepancy is within expectations, considering that training models typically outperform validation models due to the larger volume of data available for training.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(house32_new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  house32_new
BP = 1364.4, df = 5, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a>gvlma_analysis <span class="ot">&lt;-</span> <span class="fu">gvlma</span>(house32_new)</span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a>gvlma_analysis</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ bedrooms + bathrooms + sqft_living + sqft_lot + 
    waterfront, data = train_class)

Coefficients:
(Intercept)     bedrooms    bathrooms  sqft_living     sqft_lot   waterfront  
  7.416e+04   -5.896e+04    7.147e+03    3.132e+02   -3.864e-01    6.852e+05  


ASSESSMENT OF THE LINEAR MODEL ASSUMPTIONS
USING THE GLOBAL TEST ON 4 DEGREES-OF-FREEDOM:
Level of Significance =  0.05 

Call:
 gvlma(x = house32_new) 

                       Value p-value                   Decision
Global Stat        2.382e+05  0.0000 Assumptions NOT satisfied!
Skewness           1.029e+04  0.0000 Assumptions NOT satisfied!
Kurtosis           2.267e+05  0.0000 Assumptions NOT satisfied!
Link Function      1.246e+03  0.0000 Assumptions NOT satisfied!
Heteroscedasticity 1.982e-01  0.6562    Assumptions acceptable.</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="iv.-best-model-and-predicion-of-the-house-test" class="level1">
<h1>IV. Best model and Predicion of the House Test</h1>
<section id="predicting-house-test-from-the-best-model---regression-tree" class="level2">
<h2 class="anchored" data-anchor-id="predicting-house-test-from-the-best-model---regression-tree">1. Predicting House Test from the Best model - Regression Tree</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a>house_test2 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"house_test_32.csv"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(<span class="fu">t</span>(<span class="fu">names</span>(house_test2)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1]           
 [1,] "X"            
 [2,] "id"           
 [3,] "Year"         
 [4,] "Month"        
 [5,] "Day"          
 [6,] "day_of_week"  
 [7,] "bedrooms"     
 [8,] "bathrooms"    
 [9,] "sqft_living"  
[10,] "sqft_lot"     
[11,] "floors"       
[12,] "waterfront"   
[13,] "view"         
[14,] "condition"    
[15,] "grade"        
[16,] "sqft_above"   
[17,] "sqft_basement"
[18,] "yr_built"     
[19,] "yr_renovated" 
[20,] "zipcode"      
[21,] "lat"          
[22,] "long"         </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a>predicted_price <span class="ot">&lt;-</span> <span class="fu">predict</span>(regress_tr, house_test2)</span>
<span id="cb150-2"><a href="#cb150-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(<span class="fu">t</span>(predicted_price))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       [,1]
1  378377.0
2  488064.6
3  378377.0
4  378377.0
5  714467.5
6  378377.0
7  378377.0
8  488064.6
9  488064.6
10 488064.6
11 378377.0
12 378377.0
13 378377.0
14 488064.6
15 488064.6
16 994249.2
17 488064.6
18 378377.0
19 378377.0
20 714467.5</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb152"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb152-1"><a href="#cb152-1" aria-hidden="true" tabindex="-1"></a>predict_price_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(predicted_price)</span>
<span id="cb152-2"><a href="#cb152-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(predict_price_df) <span class="ot">&lt;-</span> <span class="st">"Price"</span></span>
<span id="cb152-3"><a href="#cb152-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb152-4"><a href="#cb152-4" aria-hidden="true" tabindex="-1"></a>predict <span class="ot">&lt;-</span> <span class="fu">cbind</span>(house_test2, predict_price_df)</span>
<span id="cb152-5"><a href="#cb152-5" aria-hidden="true" tabindex="-1"></a>predict</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    X         id Year Month Day day_of_week bedrooms bathrooms sqft_living
1   1 1424200070 2014     5   7           3        4      1.50        2310
2   2 8682261070 2015     4  27           1        2      2.00        1680
3   3 2891400410 2015     2  27           5        3      2.25        1820
4   4 1931300425 2014     9   8           1        3      2.50        2170
5   5 3625059120 2014    10  23           4        5      3.25        3030
6   6  952002765 2014    11  14           5        4      1.75        1720
7   7 3644100072 2014    11   7           5        2      1.00         670
8   8 4123840050 2014     6  30           1        4      2.50        2570
9   9 9560800040 2014     7  16           3        3      2.50        1800
10 10 7694200090 2015     5   4           1        3      2.50        1730
11 11 7399300510 2015     2   4           3        3      2.25        1500
12 12 7950302210 2014    11  14           5        4      2.00        2200
13 13 2695600130 2014    11  18           2        2      1.00        1250
14 14 4039701280 2015     4   8           3        3      2.25        2440
15 15  425079100 2014    12  31           3        3      2.75        1840
16 16 3793501450 2014     9  10           3        5      3.75        3860
17 17 3904950190 2014     5  27           2        3      2.25        1760
18 18 1326039061 2014    10  20           1        3      1.75        1430
19 19  626049091 2014     6  27           5        2      1.00         720
20 20 1828300100 2015     3  30           1        4      2.50        3100
   sqft_lot floors waterfront view condition grade sqft_above sqft_basement
1     13300    1.0          0    0         3     7       1890           420
2      6194    1.0          0    0         3     8       1680             0
3     99752    1.0          0    0         4     7       1820             0
4      3200    1.5          0    0         5     7       1280           890
5     20446    2.0          0    2         3     9       2130           900
6      3050    1.5          0    0         5     7       1040           680
7      2356    1.0          0    0         5     6        670             0
8      7859    2.0          0    0         3     8       2570             0
9     11034    2.0          0    0         4     8       1800             0
10     4086    2.0          0    0         3     8       1730             0
11     8100    1.0          0    0         3     7       1210           290
12     3060    1.0          0    0         3     7       1100          1100
13     4558    1.0          0    0         3     7       1250             0
14     9689    1.0          0    2         4     8       1830           610
15    68479    1.0          0    2         3     8       1340           500
16     6901    2.0          0    0         3     7       3860             0
17     4539    2.0          0    0         3     8       1760             0
18     9750    1.0          0    0         5     7       1430             0
19    11400    1.0          0    0         5     6        720             0
20     7807    2.0          0    0         3     9       3100             0
   yr_built yr_renovated zipcode     lat     long    Price
1      1950            0   98004 47.6232 -122.210 378377.0
2      2004            0   98053 47.7136 -122.030 488064.6
3      1969            0   98092 47.2838 -122.006 378377.0
4      1923            0   98103 47.6543 -122.347 378377.0
5      1976            0   98008 47.6133 -122.106 714467.5
6      1929            0   98116 47.5654 -122.384 378377.0
7      1960            0   98144 47.5918 -122.295 378377.0
8      1992            0   98038 47.3736 -122.045 488064.6
9      1987            0   98072 47.7558 -122.142 488064.6
10     2013            0   98146 47.5016 -122.341 488064.6
11     1968            0   98055 47.4632 -122.190 378377.0
12     1908         2000   98118 47.5650 -122.284 378377.0
13     1948            0   98126 47.5318 -122.379 378377.0
14     1974            0   98008 47.6141 -122.111 488064.6
15     1989            0   98014 47.6802 -121.908 488064.6
16     2003            0   98038 47.3694 -122.032 994249.2
17     1988            0   98029 47.5754 -122.013 488064.6
18     1962            0   98133 47.7441 -122.357 378377.0
19     1951            0   98133 47.7641 -122.341 378377.0
20     2003            0   98034 47.7151 -122.227 714467.5</code></pre>
</div>
</div>
</section>
<section id="conclusion-1" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-1">2. Conclusion</h2>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">2.1 Summary</h3>
<p>We decide to choose 3 model because it gave us a clear understanding and the relationship between all the variable to predict the house price. We also comparing 3 models evaluation to find out the best model out of 3 and use it to predict the House Test Data.</p>
<p><strong>The Multiple Regression Model</strong></p>
<ul>
<li><p>Training Data</p>
<ul>
<li><p>Mean Error (ME): -2.587928e-09</p></li>
<li><p>Root Mean Squared Erroe (RMSE): 218823.3</p></li>
<li><p>Mean Absolute Error (MAE): 142061</p></li>
<li><p>Mean Percentage Error (MPE): -7.85%</p></li>
<li><p>Mean Absolute Percentage Error (MAPE): 29.79%</p></li>
</ul></li>
<li><p>Validation Data</p>
<ul>
<li><p>Mean Error (ME): -817.0995</p></li>
<li><p>Root Mean Squared Erroe (RMSE): 211200.6</p></li>
<li><p>Mean Absolute Error (MAE): 141775.4</p></li>
<li><p>Mean Percentage Error (MPE): -7.62%</p></li>
<li><p>Mean Absolute Percentage Error (MAPE): 29.79%</p></li>
</ul></li>
</ul>
<p><strong>The Regression Tree Model</strong></p>
<ul>
<li><p>Training Data</p>
<ul>
<li><p>Mean Error (ME): -1.365306e-11</p></li>
<li><p>Root Mean Squared Erroe (RMSE): 233236.1</p></li>
<li><p>Mean Absolute Error (MAE): 156152.6</p></li>
<li><p>Mean Percentage Error (MPE): -14.87%</p></li>
<li><p>Mean Absolute Percentage Error (MAPE): 33.79%</p></li>
</ul></li>
<li><p>Validation Data</p>
<ul>
<li><p>Mean Error (ME): -2763.554</p></li>
<li><p>Root Mean Squared Erroe (RMSE): 244315.5</p></li>
<li><p>Mean Absolute Error (MAE): 160821.9</p></li>
<li><p>Mean Percentage Error (MPE): -15.23%</p></li>
<li><p>Mean Absolute Percentage Error (MAPE): 34.39%</p></li>
</ul></li>
</ul>
<p><strong>kNN Model</strong></p>
<ul>
<li><p>k = 9</p>
<ul>
<li><p>Training Set: 0.8182 = 81.82%</p></li>
<li><p>Validation Set: 0.7783 = 77.83%</p></li>
<li><p>This kNN model with k = 9 have the Accuracy between Training and Validation set has the smallest difference</p></li>
<li><p>k = 9: AUC = 0.767</p></li>
</ul></li>
</ul>
</section>
<section id="conclusion-2" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-2">2.2 Conclusion</h3>
<ul>
<li><p>After comparing the result of 3 model, we decide to pick the Regression Tree model to be the best model out of 3, because:</p>
<ul>
<li><p>RMSE (Training) &lt; RMSE (Validation) - (233236.1 &lt; 244315.5) –&gt; Good model</p></li>
<li><p>For kNN, the Accuracy is not too high (81.82% - Training vs 77.83% - Validation)</p></li>
<li><p>For Multiple Regression:</p>
<ul>
<li>RMSE (Training) &gt; RMSE (Validation) - (218823.3 &gt; 211200.6) –&gt; Bad model</li>
</ul></li>
</ul></li>
<li><p>Using the Regression Model, we able to predict the price of 20 new houses from the House Test data and we can see that the most valuable house is predicted at $994,249.2 which included 5 bedrooms, 3.75 bathrooms, 3860 square living and 6901 square lot.</p></li>
<li><p>Moreover, we can see that the least valuable house is $378,377, in which there are 10 houses in the list that have this similar price. Also, by comparing the most valuable house with the least valuable house, we can see that the key point that make the house more valuable is the grade given to the housing unit, based on King County grading system. The higher the better.</p></li>
<li><p>Overall, we also realized that the main aspect for the price of each house is depend on the square living of the house.</p></li>
</ul>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>